### PR TITLE
Attempted optimization on Left4Bots.InventoryManager, and *slightly* lowered tick interval of "L4BThinker" to 0.0666.

### PR DESCRIPTION
**Pull request by LeGurdah**
### First change
This change for _Left4Bots.InventoryManager_ is purely experimental -- for one thing, this means a significantly reduced amount of "if" and "else" conditions in the "foreach" loop dedicated to weighing up what items are needed. Less "if" branches in a for loop = less instructions for the CPU to keep track of while it's doing that "for" loop, and it goes vroom vroom.

Instead of incrementing after an "if" condition, it increments using an integer-casted bool version of these conditions. So if the bool is true, it's 1, and 0 otherwise. (Something I learned by complete accident while messing around in C++-styled stuff.)
A few immediately temporary, 'er, integer-casted bools will need to be used on the other hand -- but I don't think this could tax anything too roughly.

### Second change
The "L4BThinker" thinker's think interval is set to 0.0666, as entities that inherit from _CTerrorPlayer_ class (i.e. player entities in this game) are capped at a tick interval of 0.0666 seconds, or half as slow as the tick rate (an estimated 15, if I'm not mistaken from some quick math) of the game's own, 30 ticks per second.
I mainly thought slowing the thinker interval to that rate could help _slightly_ lighten the frequency if it's slowed to be equal with the player entities' halved tick rate.

Here is the [source](https://developer.valvesoftware.com/wiki/Entity_Scripts#Thinker_Functions) for how I learned of the tick rate stuff for entity-related scripting purposes in this game.
Here is another [source](https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking#Basic_networking) I checked purely so I could make absolutely certain this game's tickrate was indeed 30, and that it _couldn't_ be changed.

### Last notes
Sooner or later, I'll propose an optimization (because this one is what I'd call a "significant change") in the issues tab, revolving around how the check for Tank rocks can be hoisted out of the frequently-executing _Left4Bots.OnThinker_. This will come listed with steps on how this can be implemented, the benefits, and drawbacks worth evaluating (and a compromise as a backup plan,) hence it meriting discussion.

(Also, don't mind the # numbers referring to pull requests/issues or something in the update log for my pull. They were unintentional by way of my attempt to add flair to counting changes, not knowing it could do that instead. XvX")

### CODE REVIEW

**Comment by smilz0** [comment]
I like the first change but i am a bit perplexed about the second one tbh.
The fact is that i want the L4BThinker function to run at full tick rate. I set 0.01 but the C++ code still cap it at 0.0333 for 30 ticks per second.
I guess there is something like this:
```c++
if (interval < 0.0333)
   interval = 0.0333;
```
in the code. So by setting 0.01 i'm just telling C++ to set the lowest interval it can set without having to worry about bad floating point rounding/conversions between squirrel and C++.
I do the same with the bots main think function but, as you said, the players entities cap their think functions at half the rate, so it's 15 instead of 30. However i'm not sure that the C++ code of the entity doesn't runt at full rate and only the vscript think function is called at half the rate. If that is the case, running the L4BThinker function at 15 ticks per second might have the code miss some button pressed sometimes.
I might be wrong but i feel like this change would be a pain in the ass to test and it's probably not worth the hassle.
What you think? Can we split the changes? I think the first one can be merged very quickly as it doesn't require so much testing.

**Comment by LeGurdah** [comment]
> I like the first change but i am a bit perplexed about the second one tbh. The fact is that i want the L4BThinker function to run at full tick rate. I set 0.01 but the C++ code still cap it at 0.0333 for 30 ticks per second. I guess there is something like this:
> 
> ```c++
> if (interval < 0.0333)
>    interval = 0.0333;
> ```
> 
> in the code. So by setting 0.01 i'm just telling C++ to set the lowest interval it can set without having to worry about bad floating point rounding/conversions between squirrel and C++. I do the same with the bots main think function but, as you said, the players entities cap their think functions at half the rate, so it's 15 instead of 30. However i'm not sure that the C++ code of the entity doesn't runt at full rate and only the vscript think function is called at half the rate. If that is the case, running the L4BThinker function at 15 ticks per second might have the code miss some button pressed sometimes. I might be wrong but i feel like this change would be a pain in the ass to test and it's probably not worth the hassle. What you think? Can we split the changes? I think the first one can be merged very quickly as it doesn't require so much testing.

I'll agree to split the changes, so that way the first one can be integrated immediately (and the inventory manager timer function goes vroom-vroom.)

On the subject of the thinker interval change, yea, I understand why it would be perplexing. With that said, per the convincing reason you gave to oppose this change, I ran four quick stress tests, on this second and drastic change so I could lighten the load of testing it.

The first one had said thinker's interval set to 0.0666, and then the second where the interval was set to 0.05, just to ensure there wouldn't be any unintended side-effects. Then I tested at an interval of 0.0333, and _then_ I tested back to an interval of 0.0666. The _only_ caveat is that I didn't try other values like "0.04"/"0.0444," "0.0555," or "0.06."
I rapidly bashed and kept pressing the '3' key on a particular bot with a different throwable... and I was admittedly shocked to witness it still working at that speed. I mostly missed whenever I bashed in the milliseconds I had the pistol out. Granted, I tested this in a listen server on the very small _curling_stadium_ map.

The only differences I spotted were how subtly _quickly_ the throwable would be given, and how often the targeted bot got bashed (or what would be... what, a partly jolted camera angle to an active player?) In the first two tests, the bash-give function kicked in around the _middle_ portion of the swing frames, and said bot got bashed fairly often before the "give throwable" function kicked in. In the third test, it was instantaneous, and the chances of the bash actually occurring were minimal (_not_ non-existent, though.)
After having done these quick stress-tests, now this ironically transformed into the conundrum of "how quickly it should happen." To which my personal answer is that I'll just keep the thinker interval at the lowest interval technically possible, 0.0333. (So you may freely skip this second change. 'Twas experimental after all!)

The only other thing I walked away with from these stress tests is that the "give/swap items to/with bot" function executes in, at least, 1.5 milliseconds, and at most, a whopping 19 milliseconds (this doesn't happen often, with that said.) The average is in the ballpark of 2.3-4.0.
I might look into this one later.

**Comment by LeGurdah** [comment]
### Tweak to first change
'Kay, I quickly optimized the primary weapon check in _Left4Bots.InventoryManager_ to no longer be an "if" condition, and is added straight onto the temporary bool used to increment _Left4Bots.TeamShotguns_.
I didn't see any other plans with that "if" condition, so I could safely remove it at no cost.

One less "if" condition in the foreach loop = the CPU goes vroom vroom a little faster.

### Tweak to second change
I reverted this one back to the original value of 0.0333.

### Last notes
 I know this sucker has to get split up in order to get one change in, but on the bright side, I got to squeeze in another little optimization into _Left4Bots.InventoryManager_.

**Review by smilz0 — APPROVED** [review]

**Comment by smilz0** [comment]
Sorry i've been a bit busy. I didn't have the chance to test your changes yet but i'm pretty confident that they work so i accept them. About the L4BThinker interval i'll probably add it to the settings in the future because, according to google, modded L4D2 servers can also be set with more than 30 ticks. Idk if that also affects the vscript think functions rate but it's probably better to let the people change the interval if they want to.

**Comment by LeGurdah** [comment]
> Sorry i've been a bit busy. I didn't have the chance to test your changes yet but i'm pretty confident that they work so i accept them. About the L4BThinker interval i'll probably add it to the settings in the future because, according to google, modded L4D2 servers can also be set with more than 30 ticks. Idk if that also affects the vscript think functions rate but it's probably better to let the people change the interval if they want to.

Understandably so. We've our own lives to tend to, so 'tis okay if things take a tad longer. I appreciate the successful commit merge nonetheless!

**Pull request merged**
